name: Greeter Workflow
on:
  workflow_dispatch:
    inputs:
      person_name:
      default: 'Mona'
      type: choice
      options:
        - mad
        - dad

jobs:
  greeter_job:
    name: 'Hello'
    runs-on: ubuntu-latest
    steps:
      - name: 'greeter step'
        run: echo Hello there ${{GITHUB_ACTOR}} to ${{ inputs.person_name}}
    
